/**
 * ENCONTRO DE MULHERES — COLUNA DE VIRTUDES
 * Dados dos grupos, personagens, dicas e virtudes
 */

const GRUPOS = [
  {
    id: 1,
    cor: '#0bb4cc',
    corBg: '#e6f8fb',
    personagem: 'Ana',
    imagem: 'images/ana.png',
    referencia: '1 Samuel 1',
    versiculoCompleto: '"Derramei minha alma diante do Senhor." — 1 Samuel 1:15',
    dicas: [
      'Sofri por muito tempo sem ser ouvida.',
      'Chorei e orei fervorosamente no templo do Senhor.',
      'Um sacerdote me confundiu com uma mulher bêbada.',
      'Fiz uma promessa a Deus antes de meu filho nascer.',
    ],
    palavraVirtude: 'ORACAO',
    palavraExibir: 'ORAÇÃO',
    virtude: 'Perseverança na Oração',
    reflexao: 'Ana enfrentou anos de sofrimento e incompreensão, mas nunca desistiu de buscar a Deus. Ela nos ensina que a oração persistente e sincera transforma nossa dor em fé. Deus ouviu o clamor do coração dela — e ouve o nosso também.',
    versiculo: '"Derramei minha alma diante do Senhor." — 1 Samuel 1:15',
    perguntasReflexao: [
      'Você tem orado com persistência por algo que ainda não recebeu?',
      'Como você reage quando sente que Deus está em silêncio diante das suas orações?',
      'Você já fez uma promessa a Deus em oração? Como tem cumprido?',
    ],
  },
  {
    id: 2,
    cor: '#2d9e6a',
    corBg: '#e8f7f0',
    personagem: 'Joquebede',
    imagem: 'images/joquebede.png',
    referencia: 'Êxodo 2',
    versiculoCompleto: '"A mulher ficou grávida e deu à luz um filho... escondeu-o durante três meses." — Êxodo 2:2',
    dicas: [
      'Vivi como escrava em terra estranha.',
      'Meu povo foi oprimido por um rei que temia nossa força.',
      'Para salvar meu filho, o coloquei num cesto no rio.',
      'Fui paga para amamentar meu próprio filho nos braços da filha do faraó.',
    ],
    palavraVirtude: 'CORAGEM',
    palavraExibir: 'CORAGEM',
    virtude: 'Fé e Coragem Maternal',
    reflexao: 'Joquebede é a mãe que arriscou tudo para salvar seu filho. Em vez de sucumbir ao medo, ela agiu com fé criativa e coragem extraordinária. Ela nos ensina que o amor maternal, guiado por Deus, pode mudar o destino de uma nação.',
    versiculo: '"A mulher ficou grávida e deu à luz um filho... escondeu-o durante três meses." — Êxodo 2:2',
    perguntasReflexao: [
      'Em que momento da sua vida você precisou ter coragem para proteger alguém que ama?',
      'Como você age quando as circunstâncias parecem impossíveis e o medo quer falar mais alto?',
      'Você consegue enxergar como Deus pode usar até as situações mais difíceis para o bem?',
    ],
  },
  {
    id: 3,
    cor: '#7c5cba',
    corBg: '#f2eefc',
    personagem: 'Maria',
    imagem: 'images/maria.png',
    referencia: 'Lucas 1',
    versiculoCompleto: '"Eis aqui a serva do Senhor; faça-se em mim segundo a tua palavra." — Lucas 1:38',
    dicas: [
      'Fui escolhida para uma missão humanamente impossível.',
      'Um anjo me visitou com uma mensagem que mudou o mundo.',
      'Disse "sim" a Deus mesmo sem entender tudo.',
      'Guardava as coisas no meu coração e meditava sobre elas.',
    ],
    palavraVirtude: 'ENTREGA',
    palavraExibir: 'ENTREGA',
    virtude: 'Submissão e Disponibilidade',
    reflexao: 'Maria é o exemplo mais belo de quem coloca a vontade de Deus acima de tudo. Sem hesitar, ela entregou sua vida, seu futuro e seus planos nas mãos do Senhor. Ela nos inspira a dizer "sim" mesmo quando não entendemos o caminho.',
    versiculo: '"Eis aqui a serva do Senhor; faça-se em mim segundo a tua palavra." — Lucas 1:38',
    perguntasReflexao: [
      'Você tem dito "sim" a Deus mesmo quando não entende completamente o caminho?',
      'Qual área da sua vida é mais difícil de entregar nas mãos de Deus?',
      'Como você reage quando os planos de Deus são diferentes dos seus planos pessoais?',
    ],
  },
  {
    id: 4,
    cor: '#e04b9a',
    corBg: '#fde9f4',
    personagem: 'Rebeca',
    imagem: 'images/rebeca.png',
    referencia: 'Gênesis 24',
    versiculoCompleto: '"Beba, meu senhor. E apressou-se em abaixar o cântaro sobre o braço e deu-lhe de beber." — Gênesis 24:18',
    dicas: [
      'Fui muito hospitaleira com estranhos no poço.',
      'Ofereci água a um viajante cansado e a todos os seus camelos.',
      'Deixei minha família para me casar com alguém que nunca tinha visto.',
      'Fui escolhida como esposa pelo caráter do meu coração, não pela minha aparência.',
    ],
    palavraVirtude: 'BONDADE',
    palavraExibir: 'BONDADE',
    virtude: 'Generosidade e Iniciativa',
    reflexao: 'Rebeca se levantou e agiu — ela não esperou ser perguntada duas vezes. Seu coração generoso, pronto para servir sem calcular o custo, foi o sinal que Deus usou para guiar o servo de Abraão. Ela nos ensina que bondade genuína abre portas que nenhum plano humano conseguiria.',
    versiculo: '"Beba, meu senhor. E apressou-se em abaixar o cântaro sobre o braço e deu-lhe de beber." — Gênesis 24:18',
    perguntasReflexao: [
      'Você tem iniciativa de servir sem esperar ser solicitada ou reconhecida?',
      'Em que área da sua vida você pode exercer mais generosidade a partir desta semana?',
      'Como você reage diante de oportunidades que exigem uma decisão rápida e corajosa?',
    ],
  },
  {
    id: 5,
    cor: '#e07a28',
    corBg: '#fdf0e5',
    personagem: 'Rute',
    imagem: 'images/rute.png',
    referencia: 'Rute 1—4',
    versiculoCompleto: '"Onde quer que tu morreres, morrerei eu; e ali serei sepultada." — Rute 1:17',
    dicas: [
      'Deixei minha terra natal para trás.',
      'Acompanhei minha sogra numa jornada de fé e lealdade.',
      'Trabalhei nos campos para sustentar minha família com humildade.',
      'Minha lealdade me trouxe um novo lar, um esposo e um lugar na história da fé.',
    ],
    palavraVirtude: 'LEALDADE',
    palavraExibir: 'LEALDADE',
    virtude: 'Lealdade e Fidelidade',
    reflexao: 'Rute poderia ter voltado para o conforto do que conhecia, mas escolheu ficar. Seu amor pela sogra e seu comprometimento com o Deus de Israel revelam uma lealdade que vai além das circunstâncias. Ela nos mostra que a fidelidade é uma das maiores formas de amor.',
    versiculo: '"Onde quer que tu morreres, morrerei eu; e ali serei sepultada." — Rute 1:17',
    perguntasReflexao: [
      'Você tem sido fiel às pessoas e compromissos da sua vida mesmo quando é difícil?',
      'Em que relacionamento você precisa demonstrar mais lealdade e compromisso?',
      'Como você tem honrado e cuidado das pessoas mais velhas e vulneráveis ao seu redor?',
    ],
  },
  {
    id: 6,
    cor: '#b8922a',
    corBg: '#fdf6e7',
    personagem: 'Sara',
    imagem: 'images/sara.png',
    referencia: 'Gênesis 18; 21',
    versiculoCompleto: '"Pela fé também a própria Sara recebeu força para conceber, dando à luz já fora da idade." — Hebreus 11:11',
    dicas: [
      'Ri de uma promessa que parecia humanamente impossível.',
      'Viajei por muitas terras ao lado do meu marido, obedecendo a Deus.',
      'Esperei décadas por uma promessa que parecia não chegar.',
      'Me tornei mãe quando todos já diziam ser tarde demais.',
    ],
    palavraVirtude: 'ESPERANCA',
    palavraExibir: 'ESPERANÇA',
    virtude: 'Fé que Supera Limitações',
    reflexao: 'Sara esperou por uma promessa que demorou muito mais do que esperava. Ela riu — mas Deus cumpriu. Sua história nos ensina que as limitações humanas não são obstáculos para Deus. Quando Ele promete, Ele realiza, no tempo certo e da maneira mais surpreendente.',
    versiculo: '"Pela fé também a própria Sara recebeu força para conceber, dando à luz já fora da idade." — Hebreus 11:11',
    perguntasReflexao: [
      'Existe alguma promessa de Deus que você ainda está esperando? Como está a sua fé nesse tempo de espera?',
      'Você já riu (duvidou) de algo que Deus queria fazer na sua vida? O que aprendeu com isso?',
      'Como você tem lidado com as limitações e os "é impossível" da sua vida?',
    ],
  },
  {
    id: 7,
    cor: '#c0392b',
    corBg: '#fdecea',
    personagem: 'Lóide e Eunice',
    imagem: 'images/loide-eunice.png',
    referencia: '2 Timóteo 1:5',
    versiculoCompleto: '"Tenho remembrança da fé não fingida que há em ti, a qual habitou primeiro em tua avó Lóide e em tua mãe Eunice." — 2 Timóteo 1:5',
    dicas: [
      'Somos duas mulheres da mesma família — avó e mãe.',
      'Transmitimos a fé genuína de geração em geração.',
      'Nossa casa era um lar onde a Palavra de Deus era ensinada desde cedo.',
      'O nosso discípulo mais amado se tornou um grande pastor e companheiro do apóstolo Paulo.',
    ],
    palavraVirtude: 'LEGADO',
    palavraExibir: 'LEGADO',
    virtude: 'Fé Transmitida — Legado de Fé',
    reflexao: 'Lóide e Eunice não se limitaram a acreditar sozinhas — elas transmitiram a fé. Timóteo conheceu as Escrituras desde criança por causa delas. Elas nos lembram que o maior legado que uma mulher pode deixar não é material: é a fé viva plantada no coração das próximas gerações.',
    versiculo: '"Tenho remembrança da fé não fingida que há em ti, a qual habitou primeiro em tua avó Lóide e em tua mãe Eunice." — 2 Timóteo 1:5',
    perguntasReflexao: [
      'Que herança de fé você está transmitindo para as próximas gerações da sua família?',
      'Você está sendo um exemplo vivo de fé para as pessoas que convivem com você?',
      'Como você pode investir mais ativamente na fé de alguém mais jovem que você?',
    ],
  },
];
